### ISSUE TITLE
Scanner fails to start.

### ISSUE THREAD

**Issue by 5opr4ni** [CasparCG/media-scanner#4]
C:\casparcgserver\CasparCG 2.2.0>scanner.exe
pkg/prelude/bootstrap.js:1172
      throw error;
      ^

Error: Could not locate the bindings file. Tried:
 ? C:\snapshot\media-scanner\node_modules\leveldown\build\leveldown.node
 ? C:\snapshot\media-scanner\node_modules\leveldown\build\Debug\leveldown.node
 ? C:\snapshot\media-scanner\node_modules\leveldown\build\Release\leveldown.node

 ? C:\snapshot\media-scanner\node_modules\leveldown\out\Debug\leveldown.node
 ? C:\snapshot\media-scanner\node_modules\leveldown\Debug\leveldown.node
 ? C:\snapshot\media-scanner\node_modules\leveldown\out\Release\leveldown.node
 ? C:\snapshot\media-scanner\node_modules\leveldown\Release\leveldown.node
 ? C:\snapshot\media-scanner\node_modules\leveldown\build\default\leveldown.node

 ? C:\snapshot\media-scanner\node_modules\leveldown\compiled\8.9.0\win32\x64\lev
eldown.node
    at bindings (C:\snapshot\media-scanner\node_modules\leveldown\node_modules\b
indings\bindings.js:93:9)
    at Object.<anonymous> (C:\snapshot\media-scanner\node_modules\leveldown\leve
ldown.js:4:46)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)

**Comment by pkeuter** [comment]
@5opr4ni Just to make sure; do you have the leveldown.node file in the folder where you're starting scanner.exe?

**Comment by ronag** [comment]
@pkeuter he didn't, I didn't properly upload
